<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class CreateUserController extends Controller
{
    public function index()
    {
        $data_keluarah = [
            'BANGKA',
            'BARU',
            'ANGKE',
            'BATU AMPAR',
            'BALEKAMBANG',
            'BALI MESTER',
            'BAMBU APUS',
            'WIJAYA KUSUMA',
            'CIPINANG BESAR SELATAN',
            'CIPINANG BESAR UTARA',
            'CIPINANG CEMPEDAK',
            'ANCOL',
            'CIPINANG MUARA',
            'CIPULIR',
            'BIDARA CINA',
            'GEDONG',
            'GELORA',
            'GLODOK',
            'JOHAR BARU',
            'GONDANGDIA',
            'DURI UTARA',
            'GROGOL',
            'KEBON SIRIH',
            'GROGOL UTARA',
            'CIBUBUR',
            'KRENDANG',
            'PINANGRANTI',
            'GROGOL SELATAN',
            'GUNTUR',
            'PONDOK RANGGON',
            'PULO',
            'PULO GADUNG',
            'RAWA BARAT',
            'BENDUNGAN HILIR',
            'BINTARO',
            'SUNTER AGUNG',
            'SUNTER JAYA',
            'SUSUKAN',
            'BUKIT DURI',
            'BUNGUR',
            'CAKUNG BARAT',
            'CAKUNG TIMUR',
            'CAWANG',
            'CEGER',
            'CEMPAKA BARU',
            'CEMPAKA PUTIH BARAT',
            'CEMPAKA PUTIH TIMUR',
            'CENGKARENG BARAT',
            'CENGKARENG TIMUR',
            'TAMAN SARI',
            'TAMBORA',
            'TANAH SEREAL',
            'TUGU SELATAN',
            'TUGU UTARA',
            'UJUNG MENTENG',
            'UTAN PANJANG',
            'CIDENG',
            'CIGANJUR',
            'CIJANTUNG',
            'CIKINI',
            'CIKOKO',
            'CILANDAK BARAT',
            'CILANDAK TIMUR',
            'CILANGKAP',
            'CILILITAN',
            'CILINCING',
            'CIPAYUNG',
            'CIPEDAK',
            'CIPETE SELATAN',
            'CIPETE UTARA',
            'CIPINANG',
            'CIPINANG MELAYU',
            'CIRACAS',
            'DUKUH',
            'DUREN SAWIT',
            'DUREN TIGA',
            'DURI KEPA',
            'DURI KOSAMBI',
            'DURI PULO',
            'DURI SELATAN',
            'GALUR',
            'GAMBIR',
            'GANDARIA SELATAN',
            'GANDARIA UTARA',
            'GUNUNG',
            'GUNUNG SAHARI SELATAN',
            'GUNUNG SAHARI UTARA',
            'HALIM PERDANA KUSUMA',
            'HARAPAN MULYA',
            'JAGAKARSA',
            'JATI',
            'JATI PADANG',
            'JATIPULO',
            'JATINEGARA',
            'JATINEGARA KAUM',
            'JELAMBAR',
            'JELAMBAR BARU',
            'JEMBATAN BESI',
            'JEMBATAN LIMA',
            'JOGLO',
            'KALI ANYAR',
            'KALIBARU',
            'KALIBATA',
            'KALIDERES',
            'KALISARI',
            'KAMAL',
            'KAMAL MUARA',
            'KAMPUNG BALI',
            'KAMPUNG MELAYU',
            'KAMPUNG RAWA',
            'TENGAH',
            'KAPUK',
            'KAPUK MUARA',
            'KARANG ANYAR',
            'KARET',
            'KARET KUNINGAN',
            'KARET SEMANGGI',
            'KARET TENGSIN',
            'KARTINI',
            'KAYU MANIS',
            'KAYU PUTIH',
            'KEAGUNGAN',
            'KEBAGUSAN',
            'KEBAYORAN LAMA SELATAN',
            'KEBAYORAN LAMA UTARA',
            'KEBON BARU',
            'KEBON BAWANG',
            'KEBON JERUK',
            'KEBON KACANG',
            'KEBON KELAPA',
            'KEBON KOSONG',
            'KEBON MANGGIS',
            'KEBON MELATI',
            'KEBON PALA',
            'KEDAUNG KALI ANGKE',
            'KEDOYA SELATAN',
            'KEDOYA UTARA',
            'KELAPA DUA',
            'KELAPA DUA WETAN',
            'KELAPA GADING BARAT',
            'KELAPA GADING TIMUR',
            'KEMANGGISAN',
            'KEMAYORAN',
            'KEMBANGAN SELATAN',
            'KEMBANGAN UTARA',
            'KENARI',
            'KLENDER',
            'KOJA',
            'KOTA BAMBU SELATAN',
            'KOTA BAMBU UTARA',
            'KRAMAT',
            'KRAMATJATI',
            'KRAMAT PELA',
            'KRUKUT',
            'KUNINGAN BARAT',
            'KUNINGAN TIMUR',
            'KWITANG',
            'LAGOA',
            'LEBAK BULUS',
            'LENTENG AGUNG',
            'LUBANG BUAYA',
            'MAKASAR',
            'MALAKA JAYA',
            'MALAKA SARI',
            'MAMPANG PRAPATAN',
            'MANGGA BESAR',
            'MANGGA DUA SELATAN',
            'MANGGARAI',
            'MANGGARAI SELATAN',
            'MAPHAR',
            'MARUNDA',
            'MELAWAI',
            'MENTENG',
            'MENTENG ATAS',
            'MENTENG DALAM',
            'MERUYA SELATAN',
            'MERUYA UTARA',
            'MUNJUL',
            'PADEMANGAN BARAT',
            'PADEMANGAN TIMUR',
            'PALMERIAM',
            'PALMERAH',
            'PANCORAN',
            'PAPANGGO',
            'PASAR BARU',
            'PASAR MANGGIS',
            'PASAR MINGGU',
            'PASEBAN',
            'PEGADUNGAN',
            'PEGANGSAAN',
            'PEGANGSAAN DUA',
            'PEJAGALAN',
            'PEJATEN BARAT',
            'PEJATEN TIMUR',
            'PEKAYON',
            'PEKOJAN',
            'PELA MAMPANG',
            'PENGADEGAN',
            'PENGGILINGAN',
            'PENJARINGAN',
            'PESANGGRAHAN',
            'PETAMBURAN',
            'PETOGOGAN',
            'PETOJO SELATAN',
            'PETOJO UTARA',
            'PLUIT',
            'PONDOK BAMBU',
            'PONDOK KELAPA',
            'PONDOK KOPI',
            'PONDOK LABU',
            'PONDOK PINANG',
            'PULO GEBANG',
            'RAGUNAN',
            'RAMBUTAN',
            'RAWA BADAK SELATAN',
            'PETUKANGAN UTARA',
            'PINANGSIA',
            'PETUKANGAN SELATAN',
            'PISANGAN BARU',
            'PISANGAN TIMUR',
            'RAWA BADAK UTARA',
            'UTAN KAYU SELATAN',
            'UTAN KAYU UTARA',
            'RAWA BUAYA',
            'RAWA BUNGA',
            'RAWAJATI',
            'RAWA TERATE',
            'RAWAMANGUN',
            'RAWASARI',
            'ROA MALAKA',
            'ROROTAN',
            'SELONG',
            'SEMANAN',
            'SEMPER BARAT',
            'SEMPER TIMUR',
            'SENAYAN',
            'SENEN',
            'SERDANG',
            'SETIA BUDI',
            'SETU',
            'SLIPI',
            'SRENGSENG',
            'SRENGSENG SAWAH',
            'SUKABUMI SELATAN',
            'SUKABUMI UTARA',
            'SUKAPURA',
            'SUMUR BATU',
            'SUNGAI BAMBU',
            'TANAH TINGGI',
            'TANGKI',
            'ULUJAMI',
            'TANJUNG BARAT',
            'TANJUNG DUREN SELATAN',
            'TANJUNG DUREN UTARA',
            'TANJUNG PRIOK',
            'TEBET BARAT',
            'TEBET TIMUR',
            'TEGAL ALUR',
            'TEGAL PARANG',
            'TOMANG',
            'WARAKAS',
        ];

        for ($i = 0; $i < count($data_keluarah); $i++) {
            User::create([
                'name' => 'ADMIN-' . $data_keluarah[$i],
                'email' => 'admin' . str_replace(' ', '', strtolower($data_keluarah[$i]))  . '@dpmptsp-dki.com',
                'password' => Hash::make($data_keluarah[$i])
            ]);
        }

        echo "User Created";
    }
}
